"""
Export helpers — render system outputs as downloadable Word documents.

Proposal drafts and pre-bid reports are deliverables a proposal manager wants to
hand off in Word, not Markdown. These build a .docx in memory with python-docx
(already a project dependency) and return bytes for a download button.

Markdown handling is intentionally light: paragraphs split on blank lines, with
"- " / "* " lines rendered as bullets and "**bold**" markers stripped. The goal
is a clean, editable starting document, not a full Markdown renderer.
"""
import re
from io import BytesIO

from docx import Document as DocxDocument
from docx.shared import Pt

from src.analysis.pre_bid import PreBidAnalysis
from src.drafting.proposal import ProposalDraft

_BOLD_MARK = re.compile(r"\*\*(.+?)\*\*")


def _clean(text: str) -> str:
    """Strip lightweight Markdown markers we don't render."""
    return _BOLD_MARK.sub(r"\1", text).strip()


def _add_body(doc: DocxDocument, body: str) -> None:
    """Add a block of (lightly Markdown-y) text as paragraphs and bullets."""
    for block in body.split("\n"):
        line = block.strip()
        if not line:
            continue
        if line.startswith(("- ", "* ")):
            doc.add_paragraph(_clean(line[2:]), style="List Bullet")
        else:
            doc.add_paragraph(_clean(line))


def proposal_to_docx_bytes(draft: ProposalDraft) -> bytes:
    """Render a ProposalDraft as a .docx and return the file bytes."""
    doc = DocxDocument()
    doc.add_heading(draft.title, level=0)

    meta = doc.add_paragraph()
    run = meta.add_run(f"Drafted from: {draft.rfp_filename} · {draft.generated_at[:10]}")
    run.italic = True
    run.font.size = Pt(9)

    note = doc.add_paragraph()
    note_run = note.add_run(
        "Draft generated by the RFP Intelligence System. Review and edit before submission."
    )
    note_run.italic = True

    references: dict[str, None] = {}
    for section in draft.sections:
        doc.add_heading(section.title, level=1)
        _add_body(doc, section.content)
        if not section.grounded:
            warn = doc.add_paragraph()
            warn.add_run(
                "(Limited company evidence found for this section — review before use.)"
            ).italic = True
        for s in section.sources:
            references[s.source] = None

    if references:
        doc.add_heading("References", level=1)
        for name in references:
            doc.add_paragraph(name, style="List Bullet")

    buffer = BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


def prebid_report_to_docx_bytes(report: PreBidAnalysis) -> bytes:
    """Render a PreBidAnalysis as a .docx and return the file bytes."""
    doc = DocxDocument()
    doc.add_heading("Pre-Bid Analysis Report", level=0)
    doc.add_paragraph(f"RFP: {report.rfp_filename}")

    rec = report.bid_recommendation
    if rec is not None:
        doc.add_heading("Bid Recommendation", level=1)
        decision = doc.add_paragraph()
        decision.add_run(
            f"{rec.recommendation} (confidence {rec.confidence:.0%})"
        ).bold = True
        if rec.summary:
            doc.add_paragraph(_clean(rec.summary))

        for title, items in [
            ("Strengths", rec.strengths),
            ("Risks", rec.risks),
            ("Missing Requirements", rec.missing_requirements),
        ]:
            if not items:
                continue
            doc.add_heading(title, level=2)
            for item in items:
                doc.add_paragraph(_clean(item), style="List Bullet")

        areas = [
            (area.replace("_", " ").title(), text)
            for area, text in rec.detailed_analysis.model_dump().items()
            if text
        ]
        if areas:
            doc.add_heading("Detailed Area Assessment", level=2)
            for label, text in areas:
                p = doc.add_paragraph()
                p.add_run(f"{label}: ").bold = True
                p.add_run(_clean(text))

    s = report.coverage_summary
    total = s.fully_covered + s.partially_covered + s.not_covered
    doc.add_heading("Coverage Summary", level=1)
    summary_tbl = doc.add_table(rows=1, cols=2)
    summary_tbl.style = "Light Grid Accent 1"
    hdr = summary_tbl.rows[0].cells
    hdr[0].text, hdr[1].text = "Status", "Count"
    for label, count in [
        ("Fully Covered", s.fully_covered),
        ("Partially Covered", s.partially_covered),
        ("Not Covered", s.not_covered),
        ("Total Requirements", total),
    ]:
        row = summary_tbl.add_row().cells
        row[0].text, row[1].text = label, str(count)

    # Include a Decision column only when the user has set at least one comply value.
    has_comply = any(r.comply is not None for r in report.requirements)
    col_n = 4 if has_comply else 3

    doc.add_heading("Requirement Coverage", level=1)
    req_tbl = doc.add_table(rows=1, cols=col_n)
    req_tbl.style = "Light Grid Accent 1"
    h = req_tbl.rows[0].cells
    h[0].text, h[1].text, h[2].text = "Requirement", "Coverage", "Evidence"
    if has_comply:
        h[3].text = "Decision"

    _cov_labels = {
        "fully_covered": "Fully Covered",
        "partially_covered": "Partially Covered",
        "not_covered": "Not Covered",
    }
    _comply_labels = {"yes": "Comply", "partial": "Partial", "no": "No Bid"}
    for coverage in ("fully_covered", "partially_covered", "not_covered"):
        for r in [x for x in report.requirements if x.coverage == coverage]:
            c = req_tbl.add_row().cells
            c[0].text = r.requirement
            c[1].text = _cov_labels[coverage]
            c[2].text = r.evidence + (f"\nSource: {r.source}" if r.source else "")
            if has_comply:
                c[3].text = _comply_labels.get(r.comply, "—") if r.comply else "—"

    doc.add_heading("Clarifying Questions", level=1)
    sev_labels = {"blocker": "Blocker", "important": "Important", "nice_to_clarify": "Nice to Clarify"}
    for severity in ("blocker", "important", "nice_to_clarify"):
        qs = [q for q in report.clarifying_questions if q.severity == severity]
        if not qs:
            continue
        doc.add_heading(sev_labels[severity], level=2)
        for q in qs:
            doc.add_paragraph(q.question, style="List Bullet")

    buffer = BytesIO()
    doc.save(buffer)
    return buffer.getvalue()
