"""
Proposal drafting for the RFP Intelligence System (ambitious goal).

Given an incoming RFP and the company knowledge base, drafts a full multi-section
proposal response. Each section is generated with per-section RAG: retrieve the
KB chunks relevant to that section, then write grounded prose that cites them.

Design (mirrors the rest of the system):
  - One LLM call summarises the RFP into the needs the proposal must address.
  - For each section, retrieve company-KB evidence (relevance-gated) and draft
    grounded text. Company-specific claims must come from the evidence.
  - Sections with no real KB evidence are flagged (grounded=False) and kept
    brief — consistent with the system's "refusal over hallucination" stance.
  - Returns a Pydantic ProposalDraft; assembly to Markdown is a method on it.

This reuses retrieval (embedding search + cross-encoder rerank) and the Source citation model. It does
not redesign any locked module.
"""
from datetime import datetime, timezone

from langchain_chroma import Chroma
from langchain_core.documents import Document
from langchain_core.language_models import BaseChatModel
from pydantic import BaseModel, Field

from src import config
from src.generation.generator import Source
from src.retrieval.vector_store import search_with_scores, rerank

DEFAULT_MODEL = None  # None → use the configured provider's default model
# All overridable via .env (see .env.example).
RFP_TEXT_LIMIT = config.env_int("RFP_TEXT_LIMIT", 14000)
SECTION_RETRIEVAL_K = config.env_int("DRAFT_SECTION_RETRIEVAL_K", 4)

# Drafting uses a lower relevance floor than Q&A. Q&A's 0.4 gate exists to refuse
# rather than hallucinate on a factual question; drafting is generative and the
# writer reviews every section, so we cast a slightly wider net to assemble the
# best available company evidence per section. Genuinely irrelevant chunks are
# still filtered out.
DRAFT_RELEVANCE_THRESHOLD = config.env_float("DRAFT_RELEVANCE_THRESHOLD", 0.25)


# ---------------------------------------------------------------------------
# Section template
# ---------------------------------------------------------------------------

class SectionSpec(BaseModel):
    """A section to draft: its title, what it should contain, and how to retrieve for it."""
    title: str
    brief: str
    retrieval_query: str


DEFAULT_SECTIONS: list[SectionSpec] = [
    SectionSpec(
        title="Executive Summary",
        brief="A concise overview positioning the firm as the right partner for this RFP.",
        retrieval_query="What does the company do and what are its main strengths and differentiators?",
    ),
    SectionSpec(
        title="Company Overview",
        brief="The firm's background, history, and credentials.",
        retrieval_query="What is the company's background, history, and credentials?",
    ),
    SectionSpec(
        title="Understanding of the Requirements",
        brief="Demonstrate a clear understanding of what the client needs and the scope of work.",
        retrieval_query="What is the scope of work and the main objectives of the project?",
    ),
    SectionSpec(
        title="Proposed Approach and Methodology",
        brief="How the firm will deliver — its methodology, governance, and delivery model.",
        retrieval_query="What is the company's delivery methodology and project management approach?",
    ),
    SectionSpec(
        title="Relevant Experience",
        brief="Past projects and case studies relevant to this RFP, with outcomes.",
        retrieval_query="What past projects and relevant experience has the company delivered?",
    ),
    SectionSpec(
        title="Team and Capabilities",
        brief="Relevant capabilities, roles, and technical expertise the firm brings.",
        retrieval_query="What are the company's technical capabilities and team expertise?",
    ),
]


# ---------------------------------------------------------------------------
# Output models
# ---------------------------------------------------------------------------

class ProposalSection(BaseModel):
    """One drafted section of the proposal."""
    title: str
    content: str
    sources: list[Source] = Field(default_factory=list)
    grounded: bool = Field(
        description="True if the section was backed by real KB evidence"
    )


class ProposalDraft(BaseModel):
    """A full multi-section proposal draft."""
    rfp_filename: str
    title: str
    sections: list[ProposalSection]
    generated_at: str

    def to_markdown(self) -> str:
        """Assemble the draft into a single Markdown document."""
        lines = [
            f"# {self.title}",
            "",
            f"*Drafted from: {self.rfp_filename} · {self.generated_at[:10]}*",
            "",
            "> Draft generated by the RFP Intelligence System. Review and edit before submission.",
            "",
        ]
        all_sources: dict[str, None] = {}
        for section in self.sections:
            lines.append(f"## {section.title}")
            lines.append("")
            lines.append(section.content)
            lines.append("")
            if not section.grounded:
                lines.append("_(Limited company evidence found for this section — review before use.)_")
                lines.append("")
            if section.sources:
                cited = sorted({s.source for s in section.sources})
                for c in cited:
                    all_sources[c] = None
                lines.append(f"*Sources: {', '.join(cited)}*")
                lines.append("")
        if all_sources:
            lines += ["---", "", "### References", ""]
            lines += [f"- {name}" for name in all_sources]
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Prompts
# ---------------------------------------------------------------------------

_SUMMARY_PROMPT = """You are a proposal manager reading an incoming RFP.

Summarise, in 6-10 short bullet points, what the client is asking for: the scope,
key requirements, constraints, and any stated objectives. This summary will guide
the drafting of a proposal response.

RFP content:
{rfp_text}

Return only the bullet points."""


_SECTION_PROMPT = """You are a senior proposal writer drafting the "{section_title}" section of a response to an RFP.

Section purpose: {section_brief}

What this RFP needs (for context):
{rfp_summary}

Evidence from the company's knowledge base (the ONLY source for company facts):
{kb_context}

Write the body of this section in professional, confident proposal prose.
Rules:
- Ground every company-specific claim — projects, clients, certifications, methods, numbers — in the evidence above.
- Do NOT invent facts, client names, figures, or credentials that are not in the evidence.
- If the evidence is thin, write what is supported and keep the section brief rather than padding.
- Do not repeat the section heading. Return only the section body text."""


_NO_EVIDENCE_NOTE = (
    "Our team will provide detailed information for this section. "
    "Supporting material is being compiled."
)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _sources_from_chunks(chunks: list[Document]) -> list[Source]:
    """Build Source citations from retrieved chunks (deduped by source+index)."""
    seen: set = set()
    sources: list[Source] = []
    for c in chunks:
        key = (c.metadata.get("source"), c.metadata.get("chunk_index"))
        if key in seen:
            continue
        seen.add(key)
        sources.append(Source(
            source=c.metadata.get("source", "unknown"),
            chunk_index=c.metadata.get("chunk_index", -1),
            page=c.metadata.get("page"),
            preview=c.page_content[:150],
        ))
    return sources


def _summarize_rfp(llm: BaseChatModel, rfp_text: str) -> str:
    """One LLM call: distil the RFP into the needs the proposal must address."""
    response = llm.invoke(config.date_prefix() + _SUMMARY_PROMPT.format(rfp_text=rfp_text[:RFP_TEXT_LIMIT]))
    return response.content.strip()


def _draft_section(
    llm: BaseChatModel,
    section: SectionSpec,
    rfp_summary: str,
    vectorstore: Chroma,
) -> ProposalSection:
    """Retrieve KB evidence for one section and draft grounded prose.

    Two-stage retrieval: over-fetch by embedding similarity, gate on relevance,
    then cross-encoder rerank to the strongest SECTION_RETRIEVAL_K chunks (same
    approach as the Ask and Analyze paths).
    """
    scored = search_with_scores(
        vectorstore,
        section.retrieval_query,
        k=SECTION_RETRIEVAL_K * 4,
        filter={"source_type": "company_kb"},
    )
    survivors = [doc for doc, score in scored if score >= DRAFT_RELEVANCE_THRESHOLD]
    try:
        chunks = [doc for doc, _ in rerank(section.retrieval_query, survivors, k=SECTION_RETRIEVAL_K)]
    except Exception:
        chunks = survivors[:SECTION_RETRIEVAL_K]
    grounded = bool(chunks)
    kb_context = (
        "\n\n".join(c.page_content for c in chunks)
        if chunks
        else "No specific company evidence was retrieved for this section."
    )
    prompt = _SECTION_PROMPT.format(
        section_title=section.title,
        section_brief=section.brief,
        rfp_summary=rfp_summary,
        kb_context=kb_context,
    )
    content = llm.invoke(config.date_prefix() + prompt).content.strip()
    if not grounded and not content:
        content = _NO_EVIDENCE_NOTE
    return ProposalSection(
        title=section.title,
        content=content,
        sources=_sources_from_chunks(chunks),
        grounded=grounded,
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def draft_proposal(
    rfp_text: str,
    rfp_filename: str,
    vectorstore: Chroma,
    sections: list[SectionSpec] | None = None,
    model: str | None = DEFAULT_MODEL,
) -> ProposalDraft:
    """
    Draft a full multi-section proposal response to an incoming RFP.

    Args:
        rfp_text: Full text extracted from the RFP document.
        rfp_filename: Original filename, shown in the draft.
        vectorstore: Loaded Chroma instance of the company KB.
        sections: Sections to draft; defaults to DEFAULT_SECTIONS.
        model: Groq model identifier.

    Returns:
        A ProposalDraft with one grounded section per spec.

    Raises:
        ValueError: If rfp_text is empty.
    """
    if not rfp_text.strip():
        raise ValueError("Cannot draft a proposal from empty RFP text.")

    specs = sections if sections is not None else DEFAULT_SECTIONS
    llm = config.get_llm(model)

    rfp_summary = _summarize_rfp(llm, rfp_text)
    drafted = [_draft_section(llm, spec, rfp_summary, vectorstore) for spec in specs]

    return ProposalDraft(
        rfp_filename=rfp_filename,
        title=f"Proposal Response — {rfp_filename}",
        sections=drafted,
        generated_at=datetime.now(timezone.utc).isoformat(timespec="seconds"),
    )


def draft_single_section(
    rfp_text: str,
    section_title: str,
    vectorstore: Chroma,
    model: str | None = DEFAULT_MODEL,
) -> ProposalSection:
    """
    Regenerate a single proposal section by title.

    Args:
        rfp_text: Full text extracted from the RFP document.
        section_title: Title matching one of DEFAULT_SECTIONS (case-insensitive).
        vectorstore: Loaded Chroma instance of the company KB.
        model: Groq model identifier.

    Returns:
        A freshly drafted ProposalSection.

    Raises:
        ValueError: If rfp_text is empty or section_title doesn't match any section.
    """
    if not rfp_text.strip():
        raise ValueError("Cannot draft a section from empty RFP text.")
    spec = next(
        (s for s in DEFAULT_SECTIONS if s.title.lower() == section_title.lower()), None
    )
    if spec is None:
        valid = [s.title for s in DEFAULT_SECTIONS]
        raise ValueError(f"Unknown section '{section_title}'. Valid: {valid}")
    llm = config.get_llm(model)
    rfp_summary = _summarize_rfp(llm, rfp_text)
    return _draft_section(llm, spec, rfp_summary, vectorstore)
